services:

    #
    # Commands
    #
    apisearch.reset_index_command:
        class: Apisearch\Command\ResetIndexCommand
        arguments:
            - "@apisearch.repository_bucket"
        tags:
            - { name: console.command }

    apisearch.export_index_command:
        class: Apisearch\Command\ExportIndexCommand
        arguments:
            - "@apisearch.repository_bucket"
        tags:
            - { name: console.command }

    apisearch.import_index_command:
        class: Apisearch\Command\ImportIndexCommand
        arguments:
            - "@apisearch.repository_bucket"
        tags:
            - { name: console.command }